### ISSUE TITLE
matplotlib: required_interactive_framework deprecation fix

### ISSUE THREAD

**Issue by jdtsmith** [wookayin/python-imgcat#13]
Using imagcat as a matplotlib module backend now (since v3.6) throws the warning:

> MatplotlibDeprecationWarning: Support for FigureCanvases without a required_interactive_framework attribute was deprecated in Matplotlib 3.6 and will be removed two minor releases later.
  
Here is the [deprecation notice](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#figurecanvas-without-a-required-interactive-framework-attribute).

**Comment by jdtsmith** [comment]
The fix for this is simple:  in mpl_backend.py, uncomment the final `FigureCanvas = FigureCanvasAgg`, moving the import of the same to the top level.  I did not notice any "unwanted configuration" of matplotlib with this setup, and the deprecation notice is squashed.

**Comment by wookayin** [comment]
I see, thanks for the issue with recent matplotlib versions. Let's check whether this doesn't have a side effect (I forget why I have commented these lines out) and I will try to apply the fix soon.

**Comment by jdtsmith** [comment]
Did you find any problems with this simple fix?

**Comment by wookayin** [comment]
To reproduce:

```
MPLBACKEND="module://imgcat" python -c 'import imgcat, matplotlib.pyplot as plt; plt.show()'
MPLBACKEND="module://imgcat.mpl_backend" python -c 'import imgcat, matplotlib.pyplot as plt; plt.show()'
```
