### ISSUE TITLE
Black image is shown in iterm2 with tmux

### ISSUE THREAD

**Issue by gnvk** [wookayin/python-imgcat#15]
Not sure how to debug this :( Instead of the image, `imgcat` displays only empty lines.

macOS version: 13.1 (22C65)
iTerm2 version: 3.4.19
tmux version: 3.3a
python version: 3.10.3

**Comment by wookayin** [comment]
What data are you trying to display?

**Comment by gnvk** [comment]
> What data are you trying to display?

It doesn't matter, the same happens with any image. For example with the wikipedia penguin.

**Comment by junnplus** [comment]
I have also encountered a similar problem, but in wezterm.

**Comment by wookayin** [comment]
Can reproduce this. It worked before, so I guess TMUX has changed some protocol. Will fix soon.

**Comment by wookayin** [comment]
tmux 3.3a has broken passthrough of escape sequence. You'll need to have the following lines in your `~/.tmux.conf` for tmux 3.3a or higher:

```
set-option -g allow-passthrough on
```

**Comment by gnvk** [comment]
Thank you @wookayin!
