### ISSUE TITLE
[Feature request] pipe arg list

### ISSUE THREAD

**Issue by albanie** [wookayin/python-imgcat#2]
Great tool.  

It would be v. useful to have the option to do this:
`ls | xargs imgcat`

The main use case (at least for me) is when you want a quick visual summary from a large directory of images.  E.g.
`ls | shuf | head -n 10 | xargs imgcat`

This works with the original `imgcat`, but with `python-imgcat`, I get the following: 
`error: when reading from stdin, arg should not be given`

Thanks!

**Comment by albanie** [comment]
Closing, since can get it to work with `parallel`.  For anyone interested:
`ls | grep png | shuf | head | parallel "cat {} | imgcat"`

**Comment by sarnobat** [comment]
It would still be nice if this could be fixed to work with xargs.

**Comment by wookayin** [comment]
I had missed this issue. Actually I agree that when stdin and arg are both provided, it can simply ignore stdin, so that xargs can work. Fixed in #3.
