### ISSUE TITLE
not work on the latest stable iterm

### ISSUE THREAD

**Issue by selaselah** [wookayin/python-imgcat#5]
If not given height/width, the image will not display.
I viewer the code, perhaps the `height` and `width` para has not been working.

**Comment by selaselah** [comment]
I remove the `height/width` para in the output code, the image can display.

**Comment by wookayin** [comment]
Can you please give more details (environments, code, etc.) on how we can reproduce this? Which iTerm version are using specifically?

**Comment by EPwood** [comment]
I'm experiencing this as well on iTerm2 3.3.4; however, this looks to be resolved in the iTerm2 3.3.5 test release

**Comment by wookayin** [comment]
@EPwood Thanks for the information. @selaselah It seems that 3.3.5 stable has been released; can you check whether this happens on the new release?

**Comment by EPwood** [comment]
Tested and working as expected on iTerm2 Build 3.3.5.

**Comment by selaselah** [comment]
Yes, fixed on iTerm2 3.3.5
