### ISSUE TITLE
Run and install imgcat on server  issue

### ISSUE THREAD

**Issue by eng100200** [wookayin/python-imgcat#9]
Hello @wookayin i want to Run and install imgcat on server (linux based) to directly view images on server rather view it on Mac. I use MobaXterm to connect to server, while, my basic question is that there is any way i can install imgcat on my server to view images on server, rather, i install another software on my laptop and then run imgcat on the laptop to see images? I hope you understand my issue.

**Comment by wookayin** [comment]
Currently (as of Apr 2020) python-imgcat only works with [iTerm2] (macOS) and [kitty] (cross-platform). I have no idea about MobaXterm, so there would be no support unless it implements a common protocol such as sixel. 

[kitty]: https://sw.kovidgoyal.net/kitty/
[iTerm2]: https://www.iterm2.com/

You can use kitty on as a terminal emulator on your laptop, then imgcat would work even when the code is executed remotely (i.e. through SSH). It just prints some graphics control sequence on stdout, so as long as you have a proper terminal emulator and $TERM settings it will work well regardless it is remote or not, the server is linux or whatever.

**Comment by wookayin** [comment]
Closing as this is a question. Please feel free to comment here if you have any further issues/questions.
